### ISSUE TITLE
"//*.c" rule matches absolute path

### ISSUE THREAD

**Issue by ezyang** [ndmitchell/shake#376] opened 2015-12-29 01:53 UTC
If I write a rule matching all c files (including those in subdirectories) using the pattern `//*.c`, I in fact also match absolute paths which are NOT in my subdirectory:

```
GOOD:
Prelude Development.Shake> "//*.o" ?== "foo.o"
True
Prelude Development.Shake> "//*.o" ?== "fo/baro.o"
True
BAD:
Prelude Development.Shake> "//*.o" ?== "/fo/baro.o"
True
```
If you attempt to depend on a build product in an absolute path, your rules will spuriously match against it.

Furthermore, Shake is unclear about how needs on absolute paths are supposed to be handled in any case.

**Comment by ezyang** [comment] 2015-12-29 02:28
I have a patch.

**Comment by ezyang** [comment] 2015-12-29 02:34
PR: #377

**Comment by ndmitchell** [comment] 2015-12-29 21:21
There are a few tickets you raised, so I'll discuss the broad themes here, and then once we figure everything out here go back and update them.

So the general plan is to remove `//` and make people only use `**` - as you've seen in other tickets, `//` plays terribly with the `</>` operator. From now on, I'll discuss with `**` examples only.

The intended behaviour of `**/*.c` is meant to match _any_ `.c` file, including those with an absolute path. In general Shake can work with both absolute and relative paths just fine, it's just a matter of convention that most people are mostly building files relative to `.` and don't use absolute paths for it. If both Windows and Linux made absolute paths start with `/` I'd be open to requiring `/**` for absolute paths, but alas, that's not the Windows way at all, so would be problematic. You could potentially make `./**` work for relative paths, but it's a departure from what we currently have, and I'm a little wary of it. If `**` only matches relative paths, what would match absolute paths? `/**`?

That said, at the moment `**` has never been released in a Shake release, so we have a unique window of limited compatibility concerns, and I agree that it might not be desirable to match absolute paths, so maybe that is the way forward... I'll certainly sleep on it.

**Comment by ezyang** [comment] 2015-12-29 21:39
A few remarks:

1. I looked at the referenced systems which have `**`. For the most part, the `**` syntax descends from ant. FishEye has `**` match absolute paths; however, ant specifically states that these selectors operate on "directory trees", which means that it's impossible to match against an absolute path; the pattern is just not well-defined in that case.

2. If `//` is intended to match against ONLY absolute paths, it is in fact an excellent name for the combinator, and interacts correctly with `</>`: `"a" </> "//path"` correctly continues to match like `//path`. Of course, `/**` would have similar properties, so that would also be a reasonable way to do that. This also allays the Windows problems, except for the "minor" problem of being a backwards-incompatible change. But it seems relatively harmless to allow `//` to continue to match relative paths (that means that there must be some absolute path for it too!), and officially support it when it is the prefix of the string.

3. I think Shake SHOULD support having a set of rules which apply to absolute paths. However, I think this should be opt-in: if users write the "obvious thing" (`**.o`), it should only match within the current directory. Otherwise, a user may find it very puzzling when Shake goes off and runs a rule trying to build a source file which doesn't live in the current build tree! I think that's surprising.

4. I'm not entirely sure how Shake's canonicalizing behavior works (but it does seem to work OK; I just don't know what to expect.) But because patterns don't handle `.` and `..` directories, I agree that we should not special case `./**`.

**Comment by ndmitchell** [comment] 2016-01-15 17:06
Sorry for taking so long to get back to this code even with a pull request (my wife has been insanely busy at work, meaning my spare time hacking has plummeted to zero - but hopefully that changes in two weeks). Some remarks:

* I'm not sure what Shake does on `**.o`, I should check. I hope equivalent to `//*.o` in the old system.

* I like the idea of `//` being absolute prefix, that does work quite beautifully. I suggest when we retire `//` from normal documentation we leave that as an example of how to match an absolute prefix. Then I'm a lot less worried about changing `**`.

* If we're going with FishEye "compatible" patterns, I suggest I read the docs for that now, before making any mistakes :)

* Shake applies [`normaliseEx`](https://hackage.haskell.org/package/shake-0.15.5/docs/Development-Shake-FilePath.html#v:normaliseEx) to all `need` first, so its very rare that `.` or `..` ends up when matching a pattern.

**Comment by ndmitchell** [comment] 2016-01-15 17:07
In summary, yes, I think `**` being relative only is the right design decision. CC @snowleopard in case he has any insight, as someone who is currently writing a lot of patterns.

**Comment by snowleopard** [comment] 2016-01-15 19:35
Let's have a look at a bunch of relevant patters from Shaking up GHC:
```haskell
"//*.prl" %> \out -> do
```
This will have to be changed to `"**/*.prl"`.
```haskell
"//AutoApply.cmm" ?== src
```
This will have to be changed to `"**/AutoApply.cmm"`.
```haskell
removeFiles gmpBuildPath ["//*"]
```
This will have to be changed to `"**/*"`.
```haskell
derivedConstantsPath ++ "//*" %> \file -> do
```
This will have to be changed to `derivedConstantsPath </> "**/*"`. Although in this case we don't need to consider subdirectories, so a simpler pattern will do: `derivedConstantsPath </> "*"`
```haskell
"//autogen/*" ?== f
```
This will have to be changed to `"**/autogen/*"`.
```haskell
file "//DerivedConstants.h" ? arg "--gen-header"
```
This will have to be changed to `"**/DerivedConstants.h"`.
```haskell
removeFiles buildRootPath [libname <//> "*"]
```
This will have to be changed to `libname </> "**/*"`.

Let me know if I messed up anywhere above. Overall sounds like a lot of changes, but nothing complicated. 

One question: if I have a rule that matches `"bin/builder.exe"` and someone `need`s `"/home/ghc/bin/builder.exe"` will it match?

**Comment by ndmitchell** [comment] 2016-01-15 22:06
The plan is to support the old patterns forever so nothing will have to ever change. /home will be matched by // but not **. The **/* idiom will usually be **.

**Comment by snowleopard** [comment] 2016-01-15 22:43
As I understand `**` is safer than `//` as it will never match anything outside the tree, so I guess I would want to switch even if I'm not forced to.

> /home will be matched by // but not *

I think you misunderstood my question: if I have a relative pattern `"bin/builder.exe"` (no wildcards!) will it match an absolute path `"/home/ghc/bin/builder.exe"` if it's `need`ed?

**Comment by ezyang** [comment] 2016-01-15 23:47
It won't. Shake never relativizes paths before doing the match.

**Comment by snowleopard** [comment] 2016-01-16 00:21
Thanks. Good to know. I do have some absolute paths to builders in the build system.

**Comment by ndmitchell** [comment] 2016-04-18 19:41
Done as described.

**Closed by ndmitchell** 2016-04-18 19:41 UTC
