### ISSUE TITLE
cmd and cmd_ get slow on linux if there is a high RLIMIT_NOFILES (open files)

### ISSUE THREAD

**Issue by typetetris** [ndmitchell/shake#722] opened 2019-09-05 21:37 UTC
https://github.com/ndmitchell/shake/blob/0eda14aaea8a893524248855064a3415ab3fe67a/src/General/Process.hs#L155

Here `close_fds = True` is set, which causes https://hackage.haskell.org/package/process-1.6.5.1/docs/System-Process.html#v:createProcess to loop from 3 to the maximum file descriptor number the process might have (RLIMIT_NOFILES, ulimit -n) and calling `close` on each one.
(Can be easily confirmed by using `strace`.)

In an environment with `ulimit -n` set to 1000000, this burns 10 seconds on around 30 `cmd_`
calls on a machine used at the company I work for. (Small demo shake system, only doing
 `touch`.)

If you don't know what is going on, you have that puzzling behaviour of having a very slow build system on one machine/environment and a fast one on a different machine/environment without a clue, why that is. Even knowing, what is going on now, it is still a very surprising behaviour.

Please consider making `close_fds` configurable and change the default to `False` (at least on linux). That's the usual behaviour of most programs shelling out commands, like bash, make, etc ..

If you explain, how would like to handle that, I am glad to provide a PR.

**Comment by ndmitchell** [comment] 2019-09-06 07:31
That's horrible! And very hard to discover - well done for finding it. I set `close_fds` because in #243 @nomeata said I should. Given the performance impact, I'm inclined to set it back to `False`. However, I'm woefully ignorant here, so I'll just follow everyone else's advice 😄.

**Comment by typetetris** [comment] 2019-09-06 08:48
I suggest making `close_fds` configurable (with an parameter to `cmd_` like `Shell`.) and setting the default to `False`. I suggest `CloseFDs` as an identifier.

Of course, that's an API change, which needs to be advertised, at least in the change notes.

The database should be opened with a O_CLOEXEC flag (I need to research, how to do this with the haskell standard library.) That would address #243 a bit.

Some arguments:

* If one kept the default `close_fds = True`, the behaviour needs to be explained in the manual directly in the documentation of `cmd` and `cmd_`, as it is not the expected behaviour and has potential performance implications. The other way round, you only need explanations on a strange, rarly used flag `CloseFDs`. 

* On linux, you usually flag fds with FD_CLOEXEC which you don't want to inherit to shelled out commands, so the OS closes them for you efficiently on any exec* call. (But that's a consideration
more for the standard library.)

* Its the default behaviour of most unix programs shelling out commands.

* You could want to inherit fds to shake and from shake to a program called by shake. That's admittedly really really rare, but impossible at the moment with shake.

If this sounds convincing to you, let me know and I start working on a PR.

**Comment by ndmitchell** [comment] 2019-09-07 13:56
For "your code might slowdown by 30s in a way you'll never find" an entry in the manual is insufficient 😉. In my view the default has to change to `close_fds = False`. Adding `CloseFDs` seems a good way out, if anyone will want to use it - if you have `FD_CLOEXEC` on the database, would anyone want it? If it's never used, or likely to be a serious slowdown, we could just not provide it until someone asks for it. But I'm not going to object to it at all.

I'm convinced!

**Comment by typetetris** [comment] 2019-09-08 07:35
Okay, I'll will start working on it tomorrow.

The decision wether the database should be opened with `FD_CLOEXEC` is up to you. Should that file descriptor intentionally leak? I would say no. So mark that fd and the os will handle it for us.

(Or is there a feature, where a recursively started shake shares a database fd with its parent process? I don't know anything like that.)

**Comment by ndmitchell** [comment] 2019-09-08 07:52
If two processes open the Shake database, things will go very wrong. As a result, I use a file lock on it, which means that two Shake processes will never inadvertently share the file. I don't think it should be accessible by the child processes, but if it's hard to do, I suspect leaving it open won't cause any serious issues (but I'm mostly ignorant on these matters).

**Comment by typetetris** [comment] 2019-09-16 10:36
See #727 for the `CloseFileHandles` option.

I didn't find, where the shake database file is opened.

it is in src/Development/Shake/Internal/Core/Storage.hs and src/General/Chunks.hs somehow, but I can't see where the file is opened.

If you could point me to the right place, I would add the call setting the close_on_exec thing if it is
a posix platform.

**Comment by ndmitchell** [comment] 2019-09-16 19:54
Solved in #727.

**Comment by ndmitchell** [comment] 2019-09-16 19:55
The `openFile` call in https://github.com/ndmitchell/shake/blob/master/src/General/Chunks.hs#L108-L114 is where the file is opened.

**Comment by typetetris** [comment] 2019-09-17 10:24
Okay, I can set the flag there, but I don't know, how to write an automated test for it (at least not in a "nice" way).

I would need a way to get at the file descriptor number for the file handle of the shake database file (for example put it in the environment or in some IORef) and this code doesn't belong in production.

Do you have a suggestion, how to get that handle in a test case?

**Comment by ndmitchell** [comment] 2019-09-17 13:19
I just wouldn't bother with a test case. The cost of the the test case is too high, and the thing its testing too low value.

**Comment by typetetris** [comment] 2019-10-21 19:48
I don't understand the life time of the file handle opened in `usingChunks`.

I set the flag and wrote a test for it, getting the file handle by traversing `/proc/self/fd`, but in the child process its often already closed, but sometimes not. Seems to be asynchronously closed?

**Comment by mokus0** [comment] 2019-12-10 18:45
> I just wouldn't bother with a test case. The cost of the the test case is too high, and the thing its testing too low value.

One anecdata point about potential cost of the issue if it does slip through testing again:  I just ran into this in a large project's build and spent around 20-30 frustrating hours tracking it down, only to discover it's an issue that's been known and diagnosed for 3 months.

An easy way to reproduce is to try to anything at all in docker, which I was setting up for a CI build - the default ulimit allows something like 1M files, the build on the same host ended up being many times slower than outside docker, and consuming 800% CPU for the duration of the build (20-30 min).

**Comment by typetetris** [comment] 2019-12-10 19:46
The problem in generell is already solved in master, but not yet released.
Here we were just discussing how (and if) to test, that the file descriptor for the shake database is (should) be closed. (If its not, it shouldn't be a performance problem.)
We should have split the ticket I suppose, sorry.

**Comment by ndmitchell** [comment] 2019-12-15 13:48
Sorry @mokus0 - I should have made a release ages ago. Now done so!

If we have no immediate plan or idea how to test, maybe we should close this ticket? Or at least rename it?

**Comment by ndmitchell** [comment] 2020-05-23 19:39
Let's close. Happy to take a test, but it looks difficult. I did blog about it though, to increase awareness. https://neilmitchell.blogspot.com/2020/05/shake-019-changes-to-process-execution.html

**Closed by ndmitchell** 2020-05-23 19:39 UTC
