### ISSUE TITLE
Docker invocation hangs starting at Shake 0.18.3

### ISSUE THREAD

**Issue by gergoerdi** [ndmitchell/shake#748] opened 2020-03-09 10:26 UTC
```
import Development.Shake

main :: IO ()
main = shakeArgs shakeOptions{shakeFiles = "_build"} $ do
    phony "foo" $ do
        cmd_ (Cwd "_build") ["docker"]
          [ "run", "-it", "alpine"
          , "sh", "-c", "echo HELLO FROM DOCKER"
          ]
    want ["foo"]
```

With Shake 0.18.2 and before, I get:

```
# docker (for foo)
HELLO FROM DOCKER
Build completed in 0.14s
```

But with 0.18.3 and later:

```
# docker (for foo)
```

and then hangs.

**Comment by gergoerdi** [comment] 2020-03-09 10:35
A quick bisection shows:

```
058138fef2e5afe34a22111b2005b31300430d26 is the first bad commit
commit 058138fef2e5afe34a22111b2005b31300430d26
Author: Neil Mitchell <ndmitchell@gmail.com>
Date:   Sun May 26 11:17:45 2019 +0100

    Improve cmd on async exceptions with nested processes on Windows
```

Which is ironic because this is all on Linux.

**Comment by gergoerdi** [comment] 2020-03-09 11:39
If I take `master` as of f7190cabd1e4d6ee1baba4a2d357c4ad80784ebb and apply just the following diff, then the script from above works:

```
diff --git a/src/General/Process.hs b/src/General/Process.hs
index 52c6d7f4..18587a2f 100755
--- a/src/General/Process.hs
+++ b/src/General/Process.hs
@@ -154,7 +154,7 @@ process po = do
     let outFiles = nubOrd [x | DestFile x <- poStdout ++ poStderr]
     let inFiles = nubOrd [x | SrcFile x <- poStdin]
     withFiles WriteMode outFiles $ \outHandle -> withFiles ReadMode inFiles $ \inHandle -> do
-        let cp = (cmdSpec poCommand){cwd = poCwd, env = poEnv, create_group = True, close_fds = poCloseFds
+        let cp = (cmdSpec poCommand){cwd = poCwd, env = poEnv, create_group = isJust poTimeout, close_fds = True
                  ,std_in = fst $ stdIn inHandle poStdin
                  ,std_out = stdStream outHandle poStdout poStderr, std_err = stdStream outHandle poStderr poStdout}
         withCreateProcessCompat cp $ \inh outh errh pid ->

```

**Comment by gergoerdi** [comment] 2020-03-10 12:26
I see my pull request actually breaks one of the tests, so looks like there's a lot more subtlety to this problem. Nevertheless, the bug is real, easily reproducible at least on Linux with the script in the original ticket, and very annoying... 

If you don't have Linux dev access, just let me know if you need any extra logging output. Running with `-VVVVVVVVVV` doesn't seem to say much extra  :/ :

```
% Starting run
% Number of actions = 1
% Number of builtin rules = 9 [AlwaysRerunQ,GetDirectoryContentsQ,GetDirectoryDirsQ,DoesFileExistQ,FilesQ,GetDirectoryFilesQ,FileQ,GetEnvQ,DoesDirectoryExistQ]
% Number of user rule types = 1
% Number of user rules = 1
% Before usingLockFile on _build/.shake.lock
% After usingLockFile
% Chunk 0 [len 34] 01000100000000000000040000002000000020000000200000000000000000000000 Id 1 = (StepKey (),Loaded (Result {result = " \NUL\NUL\NUL", built = Step 32, changed = Step 32, depends = [], execution = 0.0, traces = []}))
% Chunk 1 [len 30] 0a0003000000000000000000000020000000200000002dc41c3700000000 Id 3 = (alwaysRerun,Loaded (Result {result = "", built = Step 32, changed = Step 32, depends = [], execution = 9.344e-6, traces = []}))
% Chunk 2 [len 58] 080005000000080000006275696c642e6d6b14000000000000000000000071d8c27390000000010000000200000002000000a40a313800000000 Id 5 = (build.mk,Loaded (Result {result = "\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NULq\216\194s\144\NUL\NUL\NUL\SOH\NUL\NUL\NUL", built = Step 2, changed = Step 2, depends = [], execution = 4.221e-5, traces = []}))
% Chunk 3 [len 59] 08000600000003000000666f6f0000000020000000200000000017733f0800000004000000030000000e00000090040439a71c733f646f636b6572 Id 6 = (foo,Loaded (Result {result = "", built = Step 32, changed = Step 32, depends = [[Id 3]], execution = 0.9495697, traces = [Trace {traceMessage = "docker", traceStart = 1.25902e-4, traceEnd = 0.94965595}]}))
% Chunk 4 [len 50] 000007000000000000000000000020000000200000000000000008000000040000000600000008000000fa20733ffa20733f Id 7 = (Root,Loaded (Result {result = "", built = Step 32, changed = Step 32, depends = [[Id 6]], execution = 0.0, traces = [Trace {traceMessage = "", traceStart = 0.94972193, traceEnd = 0.94972193}]}))
% Chunk 5 [len 34] 01000100000000000000040000002100000021000000210000000000000000000000 Id 1 = (StepKey (),Loaded (Result {result = "!\NUL\NUL\NUL", built = Step 33, changed = Step 33, depends = [], execution = 0.0, traces = []}))
% Chunk 6 [len 30] 0a0003000000000000000000000021000000210000003fdb223700000000 Id 3 = (alwaysRerun,Loaded (Result {result = "", built = Step 33, changed = Step 33, depends = [], execution = 9.707e-6, traces = []}))
% Chunk 7 [len 59] 08000600000003000000666f6f00000000210000002100000004ae783f0800000004000000030000000e000000ef53d93801b2783f646f636b6572 Id 6 = (foo,Loaded (Result {result = "", built = Step 33, changed = Step 33, depends = [[Id 3]], execution = 0.97140527, traces = [Trace {traceMessage = "docker", traceStart = 1.0363e-4, traceEnd = 0.9714661}]}))
% Chunk 8 [len 50] 0000070000000000000000000000210000002100000000000000080000000400000006000000080000003fb6783f3fb6783f Id 7 = (Root,Loaded (Result {result = "", built = Step 33, changed = Step 33, depends = [[Id 6]], execution = 0.0, traces = [Trace {traceMessage = "", traceStart = 0.97153085, traceEnd = 0.97153085}]}))
% Chunk 9 [len 34] 01000100000000000000040000002200000022000000220000000000000000000000 Id 1 = (StepKey (),Loaded (Result {result = "\"\NUL\NUL\NUL", built = Step 34, changed = Step 34, depends = [], execution = 0.0, traces = []}))
% Chunk 10 [len 30] 0a000300000000000000000000002200000022000000936d143700000000 Id 3 = (alwaysRerun,Loaded (Result {result = "", built = Step 34, changed = Step 34, depends = [], execution = 8.847e-6, traces = []}))
% Chunk 11 [len 59] 08000600000003000000666f6f000000002200000022000000464a6d3f0800000004000000030000000e000000d860f838314f6d3f646f636b6572 Id 6 = (foo,Loaded (Result {result = "", built = Step 34, changed = Step 34, depends = [[Id 3]], execution = 0.9269146, traces = [Trace {traceMessage = "docker", traceStart = 1.18436e-4, traceEnd = 0.9269896}]}))
% Chunk 12 [len 50] 00000700000000000000000000002200000022000000000000000800000004000000060000000800000012546d3f12546d3f Id 7 = (Root,Loaded (Result {result = "", built = Step 34, changed = Step 34, depends = [[Id 6]], execution = 0.0, traces = [Trace {traceMessage = "", traceStart = 0.92706406, traceEnd = 0.92706406}]}))
% Chunk 13 [len 34] 01000100000000000000040000002300000023000000230000000000000000000000 Id 1 = (StepKey (),Loaded (Result {result = "#\NUL\NUL\NUL", built = Step 35, changed = Step 35, depends = [], execution = 0.0, traces = []}))
% Chunk 14 [len 30] 0a000300000000000000000000002300000023000000521cc33700000000 Id 3 = (alwaysRerun,Loaded (Result {result = "", built = Step 35, changed = Step 35, depends = [], execution = 2.3259e-5, traces = []}))
% Read 15 chunks, plus 0 slop
% Found at most 8 distinct entries out of 15
% Loaded -> Running, foo
% Loaded -> Running, alwaysRerun
% Running -> Ready, alwaysRerun
    = ((),"") (changed)
# foo
cd _build; docker run -it alpine sh -c 'echo HELLO FROM DOCKER'
```

**Comment by ndmitchell** [comment] 2020-05-17 18:01
I'm confused. On Windows I need to create_group=True to make killing one process kill them all, so things clean up properly. On Linux, I also need to do that, which surprises me - I would have thought terminateProcess on a parents process would kill the child, but it doesn't seem to do so in my tests. And I can produce the error that create_group=True makes Docker stop working, but I have no idea - asked in https://stackoverflow.com/questions/61856063/spawning-a-process-with-create-group-true-set-pgid-hangs-when-starting-docke.

So it seems you can either run docker, _or_ have timeouts/async-exceptions work, not both. Therefore, I've added a flag NoProcessGroup which you should explicitly pass when running Docker. Hopefully someone will make an intelligent comment on the StackOverflow ticket and that will point to a better solution.

**Comment by ndmitchell** [comment] 2020-05-18 07:12
From StackOverflow:

> It seems to be related to -i : Keep STDIN open even if not attached: with just -t instead of -it, the hang goes away.

@gergoerdi is that flag essential for your purposes?

**Comment by gergoerdi** [comment] 2020-05-18 10:18
Well I just tried my full build pipeline without `-i` and it finished so I guess I don't need it; but tbh I'm way out of my depth here.

**Comment by proger** [comment] 2020-05-18 15:19
I have a bunch of Shake rules that run `ffmpeg` that spits stuff out on the terminal and downgrading to 0.18.2 seems to do the trick.

**Comment by ndmitchell** [comment] 2020-05-18 15:22
With Shake HEAD you'll be able to set NoProcessGroup which will fix it. So it seems that the terminal is the problem? Setting CreateGroup might also require some pipe setting? @proger does your stuff do things with stdin (like Docker is) or just the output streams?

**Comment by proger** [comment] 2020-05-18 15:33
Yes, it tries to read things from stdin by default. I found a switch that disables this behavior (`ffmpeg -nostdin`) which makes rules complete even with `0.18.5`.

**Comment by ndmitchell** [comment] 2020-05-18 15:41
OK, that starts to explain things! In almost no cases is it a good idea for a Shake binary to read from the parent stdin - that just seems dubious at best. Yet I default to saying Inherit as the stdin handle. I think switching that default so stdin defaults to a handle that I immediately close probably helps.

I also don't have any tests of running commands that read from stdin, again, because I didn't think anyone would. Time to add some, and then I can hopefully reproduce this in my test suite, without using Docker.

**Comment by ndmitchell** [comment] 2020-05-19 07:33
So, after investigating more, and reading the StackOverflow info at https://stackoverflow.com/questions/61856063/spawning-a-process-with-create-group-true-set-pgid-hangs-when-starting-docke/61881005#61881005, we can turn this from a hang to an error that input device is not a TTY by simply closing the stdin we pass Docker. That will hopefully then make people remove the `-i` flag or add `-nostdin` to ffmpeg, which is the better thing to do.

My inclination is to close stdin by default, and expose InheritStdin as an option. When you pass NoProcessGroup and InheritStdin you'll get what you had before, but most people should figure out the right command line not to use stdin.

**Comment by ndmitchell** [comment] 2020-05-19 07:49
I've pushed all these changes to HEAD. With that and a blog post explaining the breaking change of closing stdin, I think we're good. Please shout if you think we need more.

**Comment by ndmitchell** [comment] 2020-05-23 19:37
https://neilmitchell.blogspot.com/2020/05/shake-019-changes-to-process-execution.html describes the changes and 0.19 fixes the issues, so closing this ticket. Thanks for the comments and help tracking it down!

**Closed by ndmitchell** 2020-05-23 19:37 UTC
