### ISSUE TITLE
Make it possible to output verbatim cmd arguments

### ISSUE THREAD

**Issue by nkaretnikov** [ndmitchell/shake#466] opened 2016-06-16 04:56 UTC
Spent quite a while yesterday trying to understand why gcc didn't like my linker script, resulting in a generic error, while the printed command in the output worked fine. I suspected formatting issues early enough, but still some time was spent searching for the said generic error on the web. Turned out I needed to pass my ldflags as a string rather than a list of strings, so a single `unwords` did it.

I know there's a note about that in the haddocks. Still, it would be nice to dump something unambiguous. `Show` output, perhaps, if it's just value constructors, assuming it's not too verbose (haven't looked at the relevant instances, maybe it's worthless).

**Comment by nkaretnikov** [comment] 2016-06-16 05:08
(In addition to the existing output, of course.)

**Comment by ndmitchell** [comment] 2016-06-16 13:26
What about the current printing sufficient? I would expect it to differ between:

    link "-La b c"
    link -La b c

Can you give an example of the output you got from the command failure? And what that corresponded to underneath? The Show output captures a lot of internal details to Shake, but in the end it's either a `String` (for `Shell`) or `[String]`. However, I had hoped the existing show was unambiguous enough - if not, I'd like to do better.

**Comment by ndmitchell** [comment] 2017-11-07 22:30
Closing since I don't have an example to work with (please reopen if you can give the example - I'm keen to fix it if I can reproduce).

**Closed by ndmitchell** 2017-11-07 22:30 UTC
